name: Generate GitHub Snake

on:
  # Isso roda o script todo dia às 6:00 UTC (3:00 da manhã no seu fuso)
  schedule:
    - cron: "0 6 * * *"
  
  # Isso permite que você rode manualmente pela aba "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # O seu nome de usuário do GitHub
          github_user_name: Michael315-mk
          
          # Lista de arquivos .svg que serão gerados
          # Usei a paleta 'github-dark' para combinar com seu perfil preto
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-dark-chromatic.svg?palette=github-dark&color_snake=purple&color_dots=#40c463,#30a14e,#216e39

      # Esta parte pega os arquivos gerados (dist/) e os envia para o seu repositório
      - name: Auto-commit Snake animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update github snake animation"
          file_pattern: dist/*.svg
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
