name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

# ADICIONE ESTAS DUAS LINHAS:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário
          github_user_name: Michael315-mk
          
          # Usei a paleta 'nord' para combinar com seu template
          outputs: |
            dist/snake-nord.svg?palette=nord
            dist/snake-nord-blue.svg?palette=nord&color_snake=5E81AC

      # O resto do arquivo é o mesmo
      - name: Auto-commit Snake animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update github snake animation"
          file_pattern: dist/*.svg
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
